{{- if .Values.ingest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ingest
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: ingest
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: ingest
spec:
  replicas: {{ .Values.ingest.replicas }}
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      priorityClassName: loghawk-high
      terminationGracePeriodSeconds: 15
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: ingest
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: ingest
      containers:
        - name: ingest
          image: {{ .Values.ingest.image }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ingest.port }}
          resources:
            {{- toYaml .Values.ingest.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ingest.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ingest.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingest-hpa
  namespace: {{ $.Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingest
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ingest-pdb
  namespace: {{ $.Values.global.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ingest
{{- end }}
