apiVersion: v1
kind: Secret
metadata:
  name: aliyun-registry
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjcnBpLWt3Y3huODR6Ym02ZXhwa24uY24tZ3Vhbmd6aG91LnBlcnNvbmFsLmNyLmFsaXl1bmNzLmNvbSI6eyJ1c2VybmFtZSI6ImxpbnVtdW11IiwicGFzc3dvcmQiOiJsaW5oYW9zZW5AMTMxNCIsImF1dGgiOiJiR2x1ZFcxdGRXMDZiR2x1YUdGdmMyVnVRREV6TVRRPSJ9fX0=
