apiVersion: v1
kind: Secret
metadata:
  name: loghawk-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  RABBITMQ_USER: "{{ .Values.rabbitmq.user }}"
  RABBITMQ_PASS: "{{ .Values.rabbitmq.password }}"
  OPENAI_API_KEY: "{{ .Values.aiProxy.env.openaiApiKey }}"
  CHAOS_API_TOKEN: "{{ .Values.chaos.apiToken }}"
